### ISSUE TITLE
UI doesn't report success when pasting access token

### ISSUE THREAD

**Issue by makelicious** [rikukissa/stacker#53]
Could be useful if it verified the correctness of the key and indicated it by checkmark of some sort.

here's a screenshot for possible solution:

![screen shot 2018-01-18 at 11 32 13](https://user-images.githubusercontent.com/6642742/35090887-bf3f3aac-fc43-11e7-9209-bed3e299b5f9.png)

**Comment by rikukissa** [comment]
Good idea! I think I'm gonna implement it in a way that it makes a request to Github API using that token and gives you instant feedback whether it works or not. Thanks!
