### ISSUE TITLE
Refined GitHub interaction

### ISSUE THREAD

**Issue by dwijnand** [rikukissa/stacker#61]
does this extension interact nicely with Refined GitHub?

https://github.com/sindresorhus/refined-github

**Comment by rikukissa** [comment]
Hi, 

I haven't really tried to be honest. My gut feeling is that there shouldn't be any issues using these 2 extensions simultaneously.

**Comment by dwijnand** [comment]
ok thanks, when I have a chance I'll give it a shot and report back.

**Comment by rikukissa** [comment]
Awesome, thanks a lot :)

**Comment by dwijnand** [comment]
I ran into an issue (https://github.com/rikukissa/stacker/issues/62) but I think the situation is fine. I'll comment and reopen if not.
